import React, { useState, useRef, useEffect, useCallback } from 'react';
import { useLocation } from 'react-router-dom';
import html2pdf from 'html2pdf.js';
import { 
  Download, 
  Loader2, 
  Eye, 
  AlertCircle,
  Send,
  ChevronLeft,
  ChevronRight,
  FileText
} from 'lucide-react';
import InvoiceForm from '../components/layout/InvoiceForm';
import { InvoicePaper } from '../components/invoice/InvoiceTemplates';
import EmailDialog from '../components/invoice/EmailDialog';
import '../styles/invoices.css';

const Invoices = () => {
  const location = useLocation();
  const prefillData = location.state?.prefill || null;
  const autoGenerate = location.state?.autoGenerate || false;
  const [pdfUrl, setPdfUrl] = useState(null);
  const [pdfBlob, setPdfBlob] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(null);
  const [liveData, setLiveData] = useState(null);
  const [isSending, setIsSending] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const [showEmailDialog, setShowEmailDialog] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [mobileScale, setMobileScale] = useState(
    window.innerWidth <= 480 ? 0.5 : null
  );
  const [containerHeight, setContainerHeight] = useState(null);
  const invoiceRef = useRef();
  const previewContentRef = useRef(null);

  useEffect(() => {
    const el = previewContentRef.current;
    if (!el) return;

    const calc = () => {
      if (window.innerWidth <= 480) {
        const cw = el.getBoundingClientRect().width;
        if (cw > 50) {
          const paperWidth = 210 * 3.7795;
          setMobileScale(Math.min(1, (cw - 4) / paperWidth));
        }
      } else {
        setMobileScale(null);
        setContainerHeight(null);
      }
    };

    calc();
    const timer = setTimeout(calc, 150);
    const ro = new ResizeObserver(calc);
    ro.observe(el);
    window.addEventListener('resize', calc);
    return () => {
      clearTimeout(timer);
      ro.disconnect();
      window.removeEventListener('resize', calc);
    };
  }, []);

  useEffect(() => {
    if (mobileScale !== null && mobileScale < 1 && invoiceRef.current && liveData) {
      const naturalHeight = invoiceRef.current.scrollHeight || invoiceRef.current.offsetHeight;
      if (naturalHeight > 50) {
        setContainerHeight(naturalHeight * mobileScale);
        return;
      }
    }
    setContainerHeight(null);
  }, [mobileScale, liveData]);

  const handleGenerate = useCallback(async (data) => {
    if (!invoiceRef.current) return null;
    
    const currentData = data || liveData;
    if (!currentData) {
      setError('No data available to generate PDF');
      return null;
    }

    setIsGenerating(true);
    setError(null);
    
    try {
      const element = invoiceRef.current;
      const opt = {
        margin: 0,
        filename: `Invoice_${currentData?.name?.split('\n')[0] || 'ScalePods'}.pdf`,
        image: { type: 'png', quality: 1.0 },
        html2canvas: { 
          scale: 2, 
          useCORS: true,
          scrollY: 0,
          scrollX: 0,
          windowWidth: element.scrollWidth,
          windowHeight: element.scrollHeight
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: 'css' }
      };

      const rawBlob = await html2pdf().set(opt).from(element).output('blob');
      if (!rawBlob) throw new Error('Failed to capture PDF content');
      
      const blob = new Blob([rawBlob], { type: 'application/pdf' });
      setPdfBlob(blob);
      const url = URL.createObjectURL(blob);
      setPdfUrl(url);
      return blob;
      
    } catch (err) {
      setError('Failed to generate PDF locally: ' + err.message);
      console.error('PDF Generation Error:', err);
      return null;
    } finally {
      setIsGenerating(false);
    }
  }, [liveData]);

  useEffect(() => {
    if (autoGenerate && liveData && !hasAutoGenerated && invoiceRef.current) {
      setHasAutoGenerated(true);
      const timer = setTimeout(() => handleGenerate(), 500);
      return () => clearTimeout(timer);
    }
  }, [autoGenerate, liveData, hasAutoGenerated, handleGenerate]);

  const buildWebhookPayload = (eventType) => {
    if (!liveData) throw new Error('No live data available for payload');
    
    const clientName = liveData.name?.split('\n')[0] || '';
    const clientAddress = liveData.name?.split('\n').slice(1).join(', ') || '';
    const items = liveData.items || [];
    const itemsJson = JSON.stringify(items);
    const lineItemDescription = items.map(item => item.description).filter(Boolean).join(', ');
    const extraEmails = (liveData.extraEmails || []).filter(Boolean).join(', ');

    const payload = {
      event: eventType,
      invoiceType: `${(liveData.type || 'Proforma').toLowerCase().replace('proforma', 'performa')}-${(liveData.region || 'India').toLowerCase()}`,
      type: liveData.type || '',
      region: liveData.region || '',
      name: liveData.name || '',
      clientName,
      clientAddress,
      email: liveData.email || '',
      lineItemDescription,
      currency: liveData.currency || '',
      amount: liveData.amount || '',
      amountPaid: liveData.amountPaid || '',
      dueAmount: liveData.dueAmount || '',
      invoiceDate: liveData.invoiceDate || '',
      dueDate: liveData.dueDate || '',
      paymentTerm: liveData.paymentTerm || '',
      items: itemsJson,
      clientGstin: liveData.clientGstin || '',
      clientState: liveData.clientState || '',
      myGstin: liveData.myGstin || '',
      sacCode: liveData.sacCode || '',
      amountInWords: liveData.amountInWords || '',
      accHolder: liveData.accHolder || '',
      bankName: liveData.bankName || '',
      accNo: liveData.accNo || '',
      ifsc: liveData.ifsc || '',
      branch: liveData.branch || '',
      accType: liveData.accType || '',
      terms: liveData.terms || '',
    };

    if (extraEmails) {
      payload.extraEmails = extraEmails;
    }

    return payload;
  };

  const getActionType = () => {
    const typeKey = (liveData.type || 'Proforma').toLowerCase().replace('proforma', 'performa');
    const regionKey = (liveData.region || 'India').toLowerCase();
    return `${typeKey}${regionKey}`;
  };

  const handleSendToClient = async ({ subject, body }) => {
    if (!liveData) {
      alert('Error: No data to send. Please ensure form is filled.');
      return;
    }

    let currentBlob = pdfBlob;
    if (!currentBlob) {
      currentBlob = await handleGenerate();
      if (!currentBlob) {
        alert('Failed to generate PDF. Please try again.');
        return;
      }
    }

    setIsSending(true);
    try {
      const payload = buildWebhookPayload('send');
      if (subject) payload.emailSubject = subject;
      if (body) payload.emailBody = body;
      const webhookUrl = `${import.meta.env.VITE_N8N_BASE_URL}/${import.meta.env.VITE_WEBHOOK_ID_INVOICE}?action=${getActionType()}`;

      const formData = new FormData();
      formData.append('file', currentBlob, `Invoice_${liveData.name?.split('\n')[0].replace(/\s+/g, '_')}.pdf`);
      Object.entries(payload).forEach(([key, value]) => {
        formData.append(key, value);
      });

      const response = await fetch(webhookUrl, {
        method: 'POST',
        body: formData
      });

      if (response.ok) {
        setShowEmailDialog(false);
        setPdfUrl(null);
        setPdfBlob(null);
        alert('Invoice sent successfully!');
      } else {
        const errorText = await response.text();
        throw new Error(`Webhook failed: ${errorText}`);
      }
    } catch (err) {
      alert('Error: ' + err.message);
      console.error('Webhook Error:', err);
    } finally {
      setIsSending(false);
    }
  };

  const handleDownload = async () => {
    if (!pdfUrl || !liveData) {
      alert('Please generate the PDF first.');
      return;
    }
    
    try {
      const payload = buildWebhookPayload('download');
      const webhookUrl = `${import.meta.env.VITE_N8N_BASE_URL}/${import.meta.env.VITE_WEBHOOK_ID_INVOICE}?action=${getActionType()}`;
      fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      }).catch(() => {});
    } catch (e) {
      console.warn('Track download failed', e);
    }

    const link = document.createElement('a');
    link.href = pdfUrl;
    link.download = `Invoice_${liveData?.name?.split('\n')[0].replace(/\s+/g, '_')}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="invoice-generator-page">
      <div className="preview-section">
        <div className="preview-content" ref={previewContentRef} style={containerHeight ? { maxHeight: containerHeight } : {}}>
          {isGenerating && (
            <div className="preview-state loading" style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.8)', zIndex: 30, borderRadius: '24px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', backdropFilter: 'blur(4px)' }}>
              <Loader2 className="spinner" size={48} color="var(--color-primary)" />
              <p style={{ marginTop: '1rem', fontWeight: '600', color: '#fff' }}>Generating Official PDF...</p>
            </div>
          )}

          <div style={mobileScale ? { transform: `scale(${mobileScale})`, transformOrigin: 'top center', width: '210mm', margin: '0 auto' } : {}}>
            <div ref={invoiceRef} className="invoice-paper-wrapper pdf-render-mode">
              <InvoicePaper data={liveData} />
            </div>
          </div>

          {pdfUrl && (
            <div className="preview-actions-overlay success-state">
              <div className="success-message">
                <div className="success-icon">✓</div>
                <span>PDF Ready!</span>
              </div>
              <div className="button-group">
                <button className="action-btn-premium secondary" onClick={() => { setPdfUrl(null); setPdfBlob(null); }} disabled={isSending}>
                  <Eye size={18} />
                  <span>Dismiss</span>
                </button>
                <button className="action-btn-premium" onClick={() => setShowEmailDialog(true)} disabled={isSending}>
                  {isSending ? <Loader2 className="animate-spin" size={18} /> : <Send size={18} />}
                  <span>{isSending ? 'Sending...' : 'Send'}</span>
                </button>
                <button className="action-btn-premium" onClick={handleDownload}>
                  <Download size={18} />
                  <span>Download Now</span>
                </button>
              </div>
            </div>
          )}
          
          {error && (
            <div className="error-banner" style={{ marginTop: '1rem', padding: '1rem', background: 'rgba(239, 68, 68, 0.1)', color: '#ef4444', borderRadius: '12px', display: 'flex', alignItems: 'center', gap: '0.5rem', position: 'absolute', bottom: '2rem', left: '2rem', right: '2rem', zIndex: 40 }}>
              <AlertCircle size={18} />
              <span>{error}</span>
            </div>
          )}
        </div>
      </div>

      {showForm && <div className="form-drawer-overlay" onClick={() => setShowForm(false)} />}

      <button className="mobile-form-toggle" onClick={() => setShowForm(true)} aria-label="Open invoice form">
        <ChevronLeft size={20} />
      </button>

      <div className={`form-section-sidebar ${showForm ? 'open' : ''}`}>
        <div className="form-drawer-header">
          <div className="drawer-header-left">
            <FileText size={18} />
            <span>Create Invoice</span>
          </div>
          <button className="form-drawer-close" onClick={() => setShowForm(false)} aria-label="Close form drawer">
            <ChevronRight size={20} />
          </button>
        </div>
        <InvoiceForm onGenerate={handleGenerate} onUpdate={setLiveData} prefill={prefillData} />
      </div>

      <EmailDialog
        isOpen={showEmailDialog}
        onClose={() => setShowEmailDialog(false)}
        onSend={handleSendToClient}
        invoiceData={liveData}
        isSending={isSending}
      />
    </div>
  );
};

export default Invoices;
