import React, { useState, useRef, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import html2pdf from 'html2pdf.js';
import { 
  FileText, 
  Download, 
  Printer, 
  Share2, 
  Loader2, 
  Eye, 
  AlertCircle,
  Send
} from 'lucide-react';
import InvoiceForm from '../components/layout/InvoiceForm';
import { InvoicePaper } from '../components/invoice/InvoiceTemplates';
import '../styles/invoices.css';

const Invoices = () => {
  const location = useLocation();
  const prefillData = location.state?.prefill || null;
  const autoGenerate = location.state?.autoGenerate || false;
  const [pdfUrl, setPdfUrl] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(null);
  const [liveData, setLiveData] = useState(null);
  const [pdfBlob, setPdfBlob] = useState(null);
  const [isSending, setIsSending] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const invoiceRef = useRef();

  // Auto-generate PDF when navigating from All Invoices
  useEffect(() => {
    if (autoGenerate && liveData && !hasAutoGenerated && invoiceRef.current) {
      setHasAutoGenerated(true);
      // Small delay for the preview to render
      const timer = setTimeout(() => handleGenerate(), 500);
      return () => clearTimeout(timer);
    }
  }, [autoGenerate, liveData, hasAutoGenerated]);

  const handleGenerate = async () => {
    if (!invoiceRef.current) return;
    
    setIsGenerating(true);
    setError(null);
    
    try {
      const element = invoiceRef.current;
      const opt = {
        margin: 0,
        filename: `Invoice_${liveData?.name?.split('\n')[0] || 'ScalePods'}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { 
          scale: 2, 
          useCORS: true,
          letterRendering: true
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
      };

      const rawBlob = await html2pdf().set(opt).from(element).output('blob');
      const pdfBlob = new Blob([rawBlob], { type: 'application/pdf' });
      setPdfBlob(pdfBlob);
      const url = URL.createObjectURL(pdfBlob);
      setPdfUrl(url);
      
    } catch (err) {
      setError('Failed to generate PDF locally: ' + err.message);
      console.error('PDF Generation Error:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  const buildWebhookPayload = (eventType) => {
    const clientName = liveData.name?.split('\n')[0] || '';
    const clientAddress = liveData.name?.split('\n').slice(1).join(', ') || '';
    const itemsJson = JSON.stringify(liveData.items || []);

    return {
      event: eventType,
      invoiceType: `${(liveData.type || 'Proforma').toLowerCase().replace('proforma', 'performa')}-${(liveData.region || 'India').toLowerCase()}`,
      type: liveData.type || '',
      region: liveData.region || '',
      name: liveData.name || '',
      clientName,
      clientAddress,
      email: liveData.email || '',
      currency: liveData.currency || '',
      amount: liveData.amount || '',
      amountPaid: liveData.amountPaid || '',
      dueAmount: liveData.dueAmount || '',
      invoiceDate: liveData.invoiceDate || '',
      dueDate: liveData.dueDate || '',
      paymentTerm: liveData.paymentTerm || '',
      items: itemsJson,
      clientGstin: liveData.clientGstin || '',
      clientState: liveData.clientState || '',
      myGstin: liveData.myGstin || '',
      sacCode: liveData.sacCode || '',
      amountInWords: liveData.amountInWords || '',
      accHolder: liveData.accHolder || '',
      bankName: liveData.bankName || '',
      accNo: liveData.accNo || '',
      ifsc: liveData.ifsc || '',
      branch: liveData.branch || '',
      accType: liveData.accType || '',
      terms: liveData.terms || '',
    };
  };

  const sendToWebhook = async (payload) => {
    const typeKey = liveData.type.toLowerCase().replace('proforma', 'performa');
    const regionKey = liveData.region.toLowerCase();
    const actionType = `${typeKey}${regionKey}`;
    const webhookUrl = `${import.meta.env.VITE_N8N_BASE_URL}/${import.meta.env.VITE_WEBHOOK_ID_INVOICE}?action=${actionType}`;
    
    return fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
  };

  const handleSendToClient = async () => {
    if (!pdfBlob || !liveData) return;
    setIsSending(true);
    try {
      const payload = buildWebhookPayload('send');
      const response = await sendToWebhook(payload);
      if (response.ok) alert('Invoice sent successfully to client!');
      else throw new Error('Failed to send to webhook');
    } catch (err) {
      alert('Error sending to client: ' + err.message);
    } finally {
      setIsSending(false);
    }
  };

  const handleDownload = async () => {
    if (!pdfUrl || !liveData) return;
    try {
      const payload = buildWebhookPayload('download');
      sendToWebhook(payload);
    } catch (err) {}

    const link = document.createElement('a');
    link.href = pdfUrl;
    link.download = `Invoice_${liveData?.name?.split('\n')[0].replace(/\s+/g, '_')}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="invoice-generator-page">
      <div className="preview-section">
        <div className="preview-content">
          {isGenerating && (
            <div className="preview-state loading" style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.8)', zIndex: 30, borderRadius: '24px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', backdropFilter: 'blur(4px)' }}>
              <Loader2 className="spinner" size={48} color="var(--color-primary)" />
              <p style={{ marginTop: '1rem', fontWeight: '600', color: '#fff' }}>Generating Official PDF...</p>
            </div>
          )}

          <div ref={invoiceRef} className="invoice-paper-wrapper">
            <InvoicePaper data={liveData} />
          </div>

          {pdfUrl && (
            <div className="preview-actions-overlay success-state">
              <div className="success-message">
                <div className="success-icon">✓</div>
                <span>PDF Ready for Download!</span>
              </div>
              <div className="button-group">
                <button className="action-btn-premium secondary" onClick={() => { setPdfUrl(null); setPdfBlob(null); }} disabled={isSending}>
                  <Eye size={18} />
                  <span>Dismiss</span>
                </button>
                <button className="action-btn-premium" onClick={handleSendToClient} disabled={isSending} style={{ background: 'var(--color-primary-dark)' }}>
                  {isSending ? <Loader2 className="animate-spin" size={18} /> : <Send size={18} />}
                  <span>{isSending ? 'Sending...' : 'Send to Client'}</span>
                </button>
                <button className="action-btn-premium" onClick={handleDownload}>
                  <Download size={18} />
                  <span>Download Now</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      <div className="form-section-sidebar">
        <InvoiceForm onGenerate={handleGenerate} onUpdate={setLiveData} prefill={prefillData} />
      </div>
    </div>
  );
};

export default Invoices;
