import React, { useState, useRef, useEffect, useCallback } from 'react';
import { useLocation } from 'react-router-dom';
import html2pdf from 'html2pdf.js';
import { 
  Download, 
  Loader2, 
  Eye, 
  AlertCircle,
  Send
} from 'lucide-react';
import InvoiceForm from '../components/layout/InvoiceForm';
import { InvoicePaper } from '../components/invoice/InvoiceTemplates';
import '../styles/invoices.css';

const Invoices = () => {
  const location = useLocation();
  const prefillData = location.state?.prefill || null;
  const autoGenerate = location.state?.autoGenerate || false;
  const [pdfUrl, setPdfUrl] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState(null);
  const [liveData, setLiveData] = useState(null);
  const [isSending, setIsSending] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  const invoiceRef = useRef();

  const handleGenerate = useCallback(async (data) => {
    if (!invoiceRef.current) return null;
    
    const currentData = data || liveData;
    if (!currentData) {
      setError('No data available to generate PDF');
      return null;
    }

    setIsGenerating(true);
    setError(null);
    
    try {
      const element = invoiceRef.current;
      const opt = {
        margin: 0,
        filename: `Invoice_${currentData?.name?.split('\n')[0] || 'ScalePods'}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { 
          scale: 2, 
          useCORS: true,
          letterRendering: true
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
      };

      const rawBlob = await html2pdf().set(opt).from(element).output('blob');
      if (!rawBlob) throw new Error('Failed to capture PDF content');
      
      const blob = new Blob([rawBlob], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      setPdfUrl(url);
      return blob;
      
    } catch (err) {
      setError('Failed to generate PDF locally: ' + err.message);
      console.error('PDF Generation Error:', err);
      return null;
    } finally {
      setIsGenerating(false);
    }
  }, [liveData]);

  useEffect(() => {
    if (autoGenerate && liveData && !hasAutoGenerated && invoiceRef.current) {
      setHasAutoGenerated(true);
      const timer = setTimeout(() => handleGenerate(), 500);
      return () => clearTimeout(timer);
    }
  }, [autoGenerate, liveData, hasAutoGenerated, handleGenerate]);

  const buildWebhookPayload = (eventType) => {
    if (!liveData) throw new Error('No live data available for payload');
    
    const clientName = liveData.name?.split('\n')[0] || '';
    const clientAddress = liveData.name?.split('\n').slice(1).join(', ') || '';
    const items = liveData.items || [];
    const itemsJson = JSON.stringify(items);
    const lineItemDescription = items.map(item => item.description).filter(Boolean).join(', ');
    const extraEmails = (liveData.extraEmails || []).filter(Boolean).join(', ');

    const payload = {
      event: eventType,
      invoiceType: `${(liveData.type || 'Proforma').toLowerCase().replace('proforma', 'performa')}-${(liveData.region || 'India').toLowerCase()}`,
      type: liveData.type || '',
      region: liveData.region || '',
      name: liveData.name || '',
      clientName,
      clientAddress,
      email: liveData.email || '',
      lineItemDescription,
      currency: liveData.currency || '',
      amount: liveData.amount || '',
      amountPaid: liveData.amountPaid || '',
      dueAmount: liveData.dueAmount || '',
      invoiceDate: liveData.invoiceDate || '',
      dueDate: liveData.dueDate || '',
      paymentTerm: liveData.paymentTerm || '',
      items: itemsJson,
      clientGstin: liveData.clientGstin || '',
      clientState: liveData.clientState || '',
      myGstin: liveData.myGstin || '',
      sacCode: liveData.sacCode || '',
      amountInWords: liveData.amountInWords || '',
      accHolder: liveData.accHolder || '',
      bankName: liveData.bankName || '',
      accNo: liveData.accNo || '',
      ifsc: liveData.ifsc || '',
      branch: liveData.branch || '',
      accType: liveData.accType || '',
      terms: liveData.terms || '',
    };

    if (extraEmails) {
      payload.extraEmails = extraEmails;
    }

    return payload;
  };

  const handleSendToClient = async () => {
    if (!liveData) {
      alert('Error: No data to send. Please ensure form is filled.');
      return;
    }

    setIsSending(true);
    try {
      const payload = buildWebhookPayload('send');
      const webhookUrl = `${import.meta.env.VITE_N8N_BASE_URL}/${import.meta.env.VITE_WEBHOOK_ID_INVOICE}`;

      const response = await fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (response.ok) {
        alert('Invoice sent successfully!');
      } else {
        const errorText = await response.text();
        throw new Error(`Webhook failed: ${errorText}`);
      }
    } catch (err) {
      alert('Error: ' + err.message);
      console.error('Webhook Error:', err);
    } finally {
      setIsSending(false);
    }
  };

  const handleDownload = async () => {
    if (!pdfUrl || !liveData) {
      alert('Please generate the PDF first.');
      return;
    }
    
    try {
      const payload = buildWebhookPayload('download');
      const webhookUrl = `${import.meta.env.VITE_N8N_BASE_URL}/${import.meta.env.VITE_WEBHOOK_ID_INVOICE}`;
      fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      }).catch(() => {});
    } catch (e) {
      console.warn('Track download failed', e);
    }

    const link = document.createElement('a');
    link.href = pdfUrl;
    link.download = `Invoice_${liveData?.name?.split('\n')[0].replace(/\s+/g, '_')}.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="invoice-generator-page">
      <div className="preview-section">
        <div className="preview-content">
          {isGenerating && (
            <div className="preview-state loading" style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.8)', zIndex: 30, borderRadius: '24px', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', backdropFilter: 'blur(4px)' }}>
              <Loader2 className="spinner" size={48} color="var(--color-primary)" />
              <p style={{ marginTop: '1rem', fontWeight: '600', color: '#fff' }}>Generating Official PDF...</p>
            </div>
          )}

          <div ref={invoiceRef} className="invoice-paper-wrapper">
            <InvoicePaper data={liveData} />
          </div>

          {pdfUrl && (
            <div className="preview-actions-overlay success-state">
              <div className="success-message">
                <div className="success-icon">✓</div>
                <span>PDF Ready!</span>
              </div>
              <div className="button-group">
                <button className="action-btn-premium secondary" onClick={() => { setPdfUrl(null); }} disabled={isSending}>
                  <Eye size={18} />
                  <span>Dismiss</span>
                </button>
                <button className="action-btn-premium" onClick={handleSendToClient} disabled={isSending}>
                  {isSending ? <Loader2 className="animate-spin" size={18} /> : <Send size={18} />}
                  <span>{isSending ? 'Sending...' : 'Send'}</span>
                </button>
                <button className="action-btn-premium" onClick={handleDownload}>
                  <Download size={18} />
                  <span>Download Now</span>
                </button>
              </div>
            </div>
          )}
          
          {error && (
            <div className="error-banner" style={{ marginTop: '1rem', padding: '1rem', background: 'rgba(239, 68, 68, 0.1)', color: '#ef4444', borderRadius: '12px', display: 'flex', alignItems: 'center', gap: '0.5rem', position: 'absolute', bottom: '2rem', left: '2rem', right: '2rem', zIndex: 40 }}>
              <AlertCircle size={18} />
              <span>{error}</span>
            </div>
          )}
        </div>
      </div>

      <div className="form-section-sidebar">
        <InvoiceForm onGenerate={handleGenerate} onUpdate={setLiveData} prefill={prefillData} />
      </div>
    </div>
  );
};

export default Invoices;
